import 'dart:typed_data';
import 'package:restaurant_app/Presentation/entities/cotizaciones/cotizacion.dart';
import 'package:restaurant_app/Presentation/entities/cotizaciones/cotizacion_item.dart';

/// Modelo de datos: Cotizacion.
class CotizacionModel extends Cotizacion {
  const CotizacionModel({
    required super.id,
    required super.restaurantId,
    super.mesaId,
    super.idCliente,
    required super.clienteNombre,
    required super.clienteTelefono,
    required super.clienteEmail,
    super.estado,
    super.reservaLocal,
    super.personas,
    super.fechaEvento,
    super.comidaPreferida,
    super.notas,
    super.clienteEmpresa,
    super.clienteDireccion,
    super.horaEvento,
    super.lugarEvento,
    super.descuento,
    super.tasaImpuesto,
    super.origen,
    super.horaEmision,
    super.firmaNombre,
    super.firmaCargo,
    super.firmaNumeroDocumento,
    super.firmaEsImagen,
    super.firmaImagenBytes,
    required super.subtotal,
    required super.total,
    required super.createdAt,
    super.items,
  });

  factory CotizacionModel.fromMap(
    Map<String, dynamic> map, {
    List<CotizacionItem>? items,
  }) {
    return CotizacionModel(
      id: map['id'] as String,
      restaurantId: map['restaurant_id'] as String,
      mesaId: map['mesa_id'] as String?,
      idCliente: (map['id_cliente'] as num?)?.toInt(),
      clienteNombre: map['cliente_nombre'] as String,
      clienteTelefono: map['cliente_telefono'] as String,
      clienteEmail: map['cliente_email'] as String,
      estado: map['estado'] as String? ?? 'pendiente',
      reservaLocal: (map['reserva_local'] as int?) == 1,
      personas: map['personas'] as int?,
      fechaEvento: map['fecha_evento'] as String?,
      comidaPreferida: map['comida_preferida'] as String?,
      notas: map['notas'] as String?,
      clienteEmpresa: map['cliente_empresa'] as String?,
      clienteDireccion: map['cliente_direccion'] as String?,
      horaEvento: map['hora_evento'] as String?,
      lugarEvento: map['lugar_evento'] as String?,
      descuento: (map['descuento'] as num? ?? 0).toDouble(),
      tasaImpuesto: (map['tasa_impuesto'] as num? ?? 0).toDouble(),
      origen: map['origen'] as String? ?? 'publica',
      horaEmision: map['hora_emision'] as String?,
      firmaNombre: map['firma_nombre'] as String?,
      firmaCargo: map['firma_cargo'] as String?,
      firmaNumeroDocumento: map['firma_numero_documento'] as String?,
      firmaEsImagen: (map['firma_es_imagen'] as int? ?? 0) == 1,
      firmaImagenBytes: map['firma_imagen_bytes'] as Uint8List?,
      subtotal: (map['subtotal'] as num).toDouble(),
      total: (map['total'] as num).toDouble(),
      createdAt: DateTime.parse(map['created_at'] as String),
      items: items ?? const [],
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'restaurant_id': restaurantId,
      'mesa_id': mesaId,
      'id_cliente': idCliente,
      'cliente_nombre': clienteNombre,
      'cliente_telefono': clienteTelefono,
      'cliente_email': clienteEmail,
      'estado': estado,
      'reserva_local': reservaLocal ? 1 : 0,
      'personas': personas,
      'fecha_evento': fechaEvento,
      'comida_preferida': comidaPreferida,
      'notas': notas,
      'cliente_empresa': clienteEmpresa,
      'cliente_direccion': clienteDireccion,
      'hora_evento': horaEvento,
      'lugar_evento': lugarEvento,
      'descuento': descuento,
      'tasa_impuesto': tasaImpuesto,
      'origen': origen,
      'hora_emision': horaEmision,
      'firma_nombre': firmaNombre,
      'firma_cargo': firmaCargo,
      'firma_numero_documento': firmaNumeroDocumento,
      'firma_es_imagen': firmaEsImagen ? 1 : 0,
      'firma_imagen_bytes': firmaImagenBytes,
      'subtotal': subtotal,
      'total': total,
      'created_at': createdAt.toIso8601String(),
    };
  }

  factory CotizacionModel.fromEntity(Cotizacion entity) {
    return CotizacionModel(
      id: entity.id,
      restaurantId: entity.restaurantId,
      mesaId: entity.mesaId,
      idCliente: entity.idCliente,
      clienteNombre: entity.clienteNombre,
      clienteTelefono: entity.clienteTelefono,
      clienteEmail: entity.clienteEmail,
      estado: entity.estado,
      reservaLocal: entity.reservaLocal,
      personas: entity.personas,
      fechaEvento: entity.fechaEvento,
      comidaPreferida: entity.comidaPreferida,
      notas: entity.notas,
      clienteEmpresa: entity.clienteEmpresa,
      clienteDireccion: entity.clienteDireccion,
      horaEvento: entity.horaEvento,
      lugarEvento: entity.lugarEvento,
      descuento: entity.descuento,
      tasaImpuesto: entity.tasaImpuesto,
      origen: entity.origen,
      horaEmision: entity.horaEmision,
      firmaNombre: entity.firmaNombre,
      firmaCargo: entity.firmaCargo,
      firmaNumeroDocumento: entity.firmaNumeroDocumento,
      firmaEsImagen: entity.firmaEsImagen,
      firmaImagenBytes: entity.firmaImagenBytes,
      subtotal: entity.subtotal,
      total: entity.total,
      createdAt: entity.createdAt,
      items: entity.items,
    );
  }
}
